### PR TITLE
Revert CodecContext.

### PR DESCRIPTION
**Pull request by cedws**
Reverts a change deemed unnecessary. 

- [Glowstone/pull/972](https://github.com/GlowstoneMC/Glowstone/pull/972)
- [network/pull/1](https://github.com/GlowstoneMC/network/pull/1)

### CODE REVIEW

**Comment by cedws** [comment]
I think the CLA is per-repository;
*I have read and agree to the Glowstone CLA.*

**Comment by mastercoms** [comment]
Could we do a version bump to 1.2.6?

**Comment by aramperes** [comment]
I think we should just release and tag 1.2.5 after this is merged

**Comment by cedws** [comment]
Releasing 1.2.5 after 1.2.5-SNAPSHOT seems like the way to go. Anything else needed before merge?

**Review by aramperes — APPROVED** [review]

**Pull request merged**
